import Head from "next/head";
import { useState, useEffect } from "react";
import Layout from "../components/Layout";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import { ethers } from "ethers";
import { useMoralis, useWeb3Contract } from "react-moralis";
import Abi from "../constants/Abi/stakeFactory.json";

export default function Home() {
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Staketh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Layout />
    </div>
  );
}
